# Generated by Django 5.1.1 on 2024-11-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_code', models.CharField(max_length=100)),
                ('ingredient_name', models.CharField(max_length=255)),
                ('stock_quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('import_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('supplier_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
