# Generated by Django 5.1.3 on 2024-11-21 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=50)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.profile')),
            ],
            options={
                'verbose_name_plural': 'Bill Table',
            },
        ),
        migrations.CreateModel(
            name='BillDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bill')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dish')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='dishes',
            field=models.ManyToManyField(through='myapp.BillDish', to='myapp.dish'),
        ),
    ]
