# Generated by Django 5.1.3 on 2024-11-21 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_bill_options_alter_bill_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdish',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
    ]
