# Generated by Django 5.1.3 on 2024-11-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('role_id', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
