# Generated by Django 5.1.3 on 2024-11-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='staff',
        ),
    ]
