from .table_model import Table
from .bill_model import Bill
from .categorydish_model import CategoryDish
from .cookmethod_model import CookMethod
from .menu_model import Menu
from .reservation_model import Reservation
from .user_model import User
from .dishorder_model import DishOrder
from .staff_model import Staff
from .role_model import Role
from .department_model import Department
